// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_tolerances.py from tests/tolerances.toml. Do not edit: change the TOML
// and regenerate (CI checks this file is current).
//
// Tolerance register, test side (ARCHITECTURE.md §7, D-016, D-125). Tests use these names, never
// literals. Every TOL_ id here has an entry with the same id in
// docs/methodology/tolerances.md giving its value, rationale and enforcing test;
// the tolerance_register_sync test fails if the two sets of ids differ.
#pragma once

#include <cfloat>
#include <cstdint>

namespace vcal::tol {

// --- core/special (M1.2): ULP distance to the correctly rounded mpmath value ---------------------
inline constexpr std::uint64_t TOL_ERFCX_ULP = 4;
inline constexpr std::uint64_t TOL_LOG_PHI_ULP = 8;
inline constexpr double TOL_LOG_PHI_SUBNORMAL_ABS = DBL_MIN;
inline constexpr std::uint64_t TOL_PROBIT_ULP = 12;
inline constexpr std::uint64_t TOL_LBINOM_ULP = 4;
inline constexpr std::uint64_t TOL_STIRLING_ERROR_ULP = 4;
inline constexpr std::uint64_t TOL_LOG_ADD_EXP_ULP = 2;
inline constexpr std::uint64_t TOL_INVERSE_MILLS_ULP = 8;

// --- core/quadrature (M1.3): "eps" = DBL_EPSILON x max(1, |expected|) on log scale ---------------
inline constexpr double TOL_GH_MOMENT_EPS_PER_DEGREE = 5;
inline constexpr double TOL_GH_ODD_MOMENT_EPS = 1;
inline constexpr double TOL_AGH_GAUSSIAN_EPS = 4;
// Adaptive GH on binomial-mixture integrals, by measured regime (D-086, D-088):
// A: full precision, 0 < d < n.
inline constexpr double TOL_AGH_REGIME_A_MAX_RHO = 0.24;
inline constexpr int TOL_AGH_REGIME_A_MIN_N = 64;
inline constexpr double TOL_AGH_REGIME_A_EPS = 5;
// B: rho up to 0.5. Both regimes cover periods with 0 < d < n only (D-116).
inline constexpr double TOL_AGH_REGIME_B_MAX_RHO = 0.5;
inline constexpr int TOL_AGH_REGIME_B_MIN_N = 128;
inline constexpr double TOL_AGH_REGIME_B_EPS = 5;
// The parity rule (adaptive GH for 0 < d < n, composite Gauss-Legendre for d in {0, n}, D-118)
// against mpmath on every golden case, rho up to 0.99.
inline constexpr double TOL_PARITY_MIXTURE_EPS = 24;
// Per-period |rule - doubled rule| in log L_t above which a period counts as inaccurate in the
// check-contract tests (D-092). The engine's own threshold is max(this, 64 eps x term size),
// D-120; the tests require that no period with a larger true error goes unflagged.
inline constexpr double TOL_QUAD_CHECK_FLAG_ABS = 1e-10;
// The check can understate the true error when the doubled rule is itself inaccurate; over the
// golden set it never reports less than this fraction of the true error.
inline constexpr double TOL_QUAD_CHECK_MIN_DETECTION_RATIO = 0.5;

// --- grid and engine (M1.4) ----------------------------------------------------------------------
inline constexpr std::uint64_t TOL_GRID_ROUND_TRIP_ULP = 26;
inline constexpr double TOL_GRID_JACOBIAN_FD_REL = 3e-8;
inline constexpr double TOL_REFINE_QUADRATIC_ABS = 2e-15;
inline constexpr double TOL_REFINE_QUADRATIC_REL = 2e-15;
inline constexpr double TOL_REFINE_VS_FINE_GRID_SE = 0.025;
inline constexpr double TOL_SE_COARSE_VS_FINE_REL = 0.01;
inline constexpr double TOL_SE_STEP_SENSITIVITY_REL = 1e-4;

// --- ref/ against mpmath (M1.5) ------------------------------------------------------------------
inline constexpr std::uint64_t TOL_REF_LOG_NCDF_ULP = 22;
inline constexpr std::uint64_t TOL_REF_NCDF_INV_ULP = 8;
inline constexpr std::uint64_t TOL_REF_LCHOOSE_ULP = 2;
inline constexpr double TOL_REF_LOG_MIXTURE_EPS = 15;

// --- dgp/ (M1.6) ---------------------------------------------------------------------------------
inline constexpr std::uint64_t TOL_DGP_LOG_ULP = 2;
inline constexpr std::uint64_t TOL_DGP_EXP_ULP = 2;
inline constexpr std::uint64_t TOL_DGP_NCDF_ULP = 1000;
inline constexpr std::uint64_t TOL_DGP_PROBIT_ULP = 12;
inline constexpr double TOL_DGP_MOMENT_Z = 4;

// --- cross-reference, M1.7: four comparisons, never interchangeable (D-107) ----------------------
// 1. per-period l_t, core (the parity rule) vs ref, every period, term-scaled eps
inline constexpr double TOL_XREF_PERIOD_LL_EPS = 71;
// Smoothness of zero-default surfaces: second differences core vs ref, relative to the largest
inline constexpr double TOL_XREF_SURFACE_SECOND_DIFF_REL = 1e-13;
// 2. estimates, core vs ref, units of core's SE; SEs relative
inline constexpr double TOL_XREF_ESTIMATE_SE = 0.06;
inline constexpr double TOL_XREF_SE_REL = 0.032;
inline constexpr double TOL_XREF_REF_BOUND_REL = 1e-6;
// 3. core across platforms vs its own regression values (D-102)
inline constexpr double TOL_XREF_CROSS_PLATFORM_REL = 1e-12;
// 4. core's SEs across platforms vs its regression values: second differences amplify libm
//    differences, so SEs get their own tolerance (D-107, added with Q17)
inline constexpr double TOL_XREF_CROSS_PLATFORM_SE_REL = 1e-10;

// --- recovery harness, M1.8 (D-121) --------------------------------------------------------------
// Monte Carlo band for conditional coverage: 0.95 +- z sqrt(0.95 * 0.05 / m). z = 3.29 is the
// two-sided 0.1% normal quantile: over 162 scenario-parameter verdicts, 0.16 false FAILs expected.
inline constexpr double TOL_RECOVERY_COVERAGE_BAND_Z = 3.29;
// At or above this flagged fraction the coverage verdict is DEFERRED to M2 (owner's criterion).
inline constexpr double TOL_RECOVERY_MAX_FLAGGED_FRACTION = 0.05;
// recovery_harness --check on a platform other than the one that wrote the goldens: flagged and
// covered counts may differ by this many replicates. A replicate within ~1e-12 of a threshold
// (the 2-SE near-bound test, an interval end) can fall either side under libm differences.
inline constexpr std::int64_t TOL_RECOVERY_CROSS_PLATFORM_COUNT = 2;
// Replay of the recovery panels on another platform (D-107: its own comparison, not M1.7's).
// These panels reach n = 1e4, whose log-likelihood terms are ~1e5 in size; the Hessian's second
// differences at step 0.15 SE divide their last-digit libm differences by ~0.02, so SEs spread
// more than on the M1.7 panels (n = 1000).
inline constexpr double TOL_RECOVERY_REPLAY_REL = 1e-12;
inline constexpr double TOL_RECOVERY_REPLAY_SE_REL = 5e-10;

// --- scipy replication, M1.9: a plain scipy script against the engine (D-126) --------------------
// 5. The fifth kind of comparison (D-107): validation/scipy/binomial_mixture_mle.py, built from
//    ordinary tools, against the engine's committed results. Read by the script from
//    tests/tolerances.toml; not used by the C++ tests.
// Panel log-likelihood at the engine's surface points, relative. 10x the per-period accuracy the
// script requests from quad (epsrel 1e-12); observed 4.1e-13 on Windows.
inline constexpr double TOL_SCIPY_SURFACE_LL_REL = 1e-11;
// |log-likelihood at scipy's own optimum - at the engine's estimate|, both evaluated by scipy.
// The engine's sub-grid refinement costs ~z^2/2 at z ~ 0.025 SE; observed 3.9e-4, doubled.
inline constexpr double TOL_SCIPY_OPTIMUM_LL_ABS = 1e-3;
// Estimates, scipy's optimum vs the engine's, in units of the engine's SE; observed 0.0255, doubled.
inline constexpr double TOL_SCIPY_ESTIMATE_SE = 0.06;
// S-23: the end points of the 99.9% conditional PD's profile interval on the 162 recovery replay
// panels, scipy (trapezoid integrals, nested bounded Brent, brentq) vs the engine, in logit(q).
// Observed 1.2e-9: both solvers' 1e-9 tolerances. Doubled and rounded up.
inline constexpr double TOL_SCIPY_Q_PROFILE_ENDPOINT_S = 3e-9;

// --- profile likelihood, M2 (D-128..D-130) -------------------------------------------------------
// |P_a(endpoint) - (l_max - c)| in log-likelihood units, against an independent dense profile;
// also bounds the polished maximum l_max against a dense nested maximisation. Asserted on every fit
// of the recovery harness. Observed 2.1e-9 on the M1.4 test panel, 1.7e-8 worst over the 81,000
// recovery fits (steeper profiles at n = 1e4): the 1e-9 root tolerance in u times the slope.
inline constexpr double TOL_PROFILE_ENDPOINT_RESIDUAL_LL = 1e-7;
// Profile-interval endpoints, core vs ref, in logit units: the two solvers' tolerances (core 1e-9,
// ref 1e-10) with margin. Observed 1.5e-10.
inline constexpr double TOL_XREF_PROFILE_ENDPOINT_U = 2e-9;
// Profile endpoints across platforms vs regression values, relative. The root is solved to
// 1e-9 in logit units; a last-digit difference can move Brent's path anywhere inside that, and
// in logit coordinates a shift du changes v by at most v du, so 10x the solver tolerance.
inline constexpr double TOL_PROFILE_CROSS_PLATFORM_REL = 1e-8;

// --- conditional PD, S-23 ------------------------------------------------------------------------
// q = Phi((Phi^-1(PD) + sqrt(rho) z_0.999) / sqrt(1 - rho)) and logit(q) against mpmath (40 digits),
// relative, at the recovery truths and the box corners. Observed 2.9e-15 (MSVC), doubled and rounded up.
inline constexpr double TOL_CONDITIONAL_PD_REL = 6e-15;
// The analytic gradient of logit(q) in the logit coordinates against central differences (step
// 1e-5), relative. The differences' own O(h^2) error dominates: observed 4.9e-10, doubled and rounded up.
inline constexpr double TOL_CONDITIONAL_PD_GRADIENT_REL = 1e-9;

// --- resampling, M2b (D-132..D-135) --------------------------------------------------------------
// A replicate's estimate (W x L) vs calibrate on the explicitly resampled panel, relative. Only
// summation order differs (count x l_t against l_t repeated), amplified by the stencil's differences.
// Observed 0 (iid and moving block, 8 replicates each); a bound, not zero, since agreement is not
// guaranteed by construction.
inline constexpr double TOL_RESAMPLE_VS_REFIT_REL = 1e-12;
// Bootstrap percentile-interval ends of the recovery replay across platforms, relative. Each end
// interpolates two replicate estimates; a last-digit difference can reorder near-equal ones or move
// a replicate's refinement. Observed on Linux (GCC 11/14, Clang 18): 8.8e-12, doubled and rounded up.
inline constexpr double TOL_BOOTSTRAP_CROSS_PLATFORM_REL = 2e-11;
}  // namespace vcal::tol
