# SPDX-License-Identifier: Apache-2.0
#
# vcal_add_cxx17_header_check(<target> OUTPUT <file> HEADERS <abs paths>... [LANGUAGE CXX|CUDA]
#                             [EXCLUDE_FROM_ALL])
#   Generates a TU that includes every listed header and compiles it as C++17: with the host
#   compiler and the project warning set (LANGUAGE CXX, the default), or with nvcc
#   (LANGUAGE CUDA; OUTPUT must end in .cu) (D-058, D-062, D-064).
function(vcal_add_cxx17_header_check target)
    cmake_parse_arguments(ARG "EXCLUDE_FROM_ALL" "OUTPUT;LANGUAGE" "HEADERS" ${ARGN})
    if(NOT ARG_LANGUAGE)
        set(ARG_LANGUAGE CXX)
    endif()
    set(_body "// Generated by tests/cxx17/check_headers.cmake. Do not edit.\n")
    foreach(_h IN LISTS ARG_HEADERS)
        string(APPEND _body "#include \"${_h}\"\n")
    endforeach()
    string(APPEND _body "int vcal_cxx17_header_check_anchor = 0;\n")
    file(GENERATE OUTPUT "${ARG_OUTPUT}" CONTENT "${_body}")

    if(ARG_EXCLUDE_FROM_ALL)
        add_library(${target} OBJECT EXCLUDE_FROM_ALL "${ARG_OUTPUT}")
    else()
        add_library(${target} OBJECT "${ARG_OUTPUT}")
    endif()
    target_include_directories(${target} PRIVATE "${PROJECT_SOURCE_DIR}")
    if(ARG_LANGUAGE STREQUAL "CUDA")
        vcal_cuda_target_defaults(${target})
    else()
        vcal_target_defaults(${target} CXX17)
    endif()
endfunction()
