# SPDX-License-Identifier: Apache-2.0
"""Render tests/tolerances.hpp from tests/tolerances.toml (D-016, D-125).

tests/tolerances.toml is the single source of every tolerance value. C++ tests use the
generated header; validation scripts (validation/scipy/) read the TOML directly, so a
replication script never has to parse C++. Standard library only (tomllib, Python >= 3.11).

    python tools/gen_tolerances.py           write tests/tolerances.hpp
    python tools/gen_tolerances.py --check   fail if the committed header is stale
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = "tests/tolerances.toml"
TARGET = "tests/tolerances.hpp"
CXX_TYPES = {"uint64": "std::uint64_t", "int64": "std::int64_t", "int": "int", "double": "double"}
WIDTH = 100

PREAMBLE = """\
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_tolerances.py from tests/tolerances.toml. Do not edit: change the TOML
// and regenerate (CI checks this file is current).
//
// Tolerance register, test side (ARCHITECTURE.md §7, D-016, D-125). Tests use these names, never
// literals. Every TOL_ id here has an entry with the same id in
// docs/methodology/tolerances.md giving its value, rationale and enforcing test;
// the tolerance_register_sync test fails if the two sets of ids differ.
#pragma once

#include <cfloat>
#include <cstdint>

namespace vcal::tol {
"""


def shortest(v: float) -> str:
    """The shortest decimal literal that reads back as exactly v: 3e-8, not 3e-08 or 0.00000003."""
    fixed = repr(v)
    fixed = fixed[:-2] if fixed.endswith(".0") else fixed
    for digits in range(17):
        sci = f"{v:.{digits}e}"
        if float(sci) == v:
            mantissa, exponent = sci.split("e")
            sci = f"{mantissa}e{int(exponent)}"
            break
    return sci if len(sci) < len(fixed) else fixed


def literal(entry: dict) -> str:
    if "cxx" in entry:
        return entry["cxx"]
    value = entry["value"]
    if entry["type"] == "double":
        return shortest(float(value))
    if not isinstance(value, int) or isinstance(value, bool):
        raise ValueError(f"integer tolerance expected, got {value!r}")
    return str(value)


def render(table: dict) -> str:
    lines = [PREAMBLE.rstrip("\n")]
    section = None
    for name, entry in table.items():
        if not name.startswith("TOL_"):
            raise ValueError(f"{name}: tolerance ids start with TOL_")
        if entry["type"] not in CXX_TYPES:
            raise ValueError(f"{name}: unknown type {entry['type']!r}")
        if entry["section"] != section:
            section = entry["section"]
            head = f"// --- {section} "
            lines += ["", head + "-" * max(4, WIDTH - len(head))]
        lines += [f"// {c}" if c else "//" for c in entry.get("comment", [])]
        lines.append(f"inline constexpr {CXX_TYPES[entry['type']]} {name} = {literal(entry)};")
    lines += ["}  // namespace vcal::tol", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Render tests/tolerances.hpp from tests/tolerances.toml")
    parser.add_argument("--check", action="store_true", help="compare instead of writing")
    args = parser.parse_args()
    with open(ROOT / SOURCE, "rb") as f:
        text = render(tomllib.load(f))
    target = ROOT / TARGET
    if args.check:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current != text:
            print(f"{TARGET} is stale: run python tools/gen_tolerances.py", file=sys.stderr)
            return 1
        print("generated files are up to date")
        return 0
    target.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
