# SPDX-License-Identifier: Apache-2.0
"""Shared machinery for the table generators in tools/ (D-033, D-067, D-073, D-075).

- binary64 conversion and exact hex output
- mpmath reference functions used by more than one generator
- the write / --check driver and the provenance manifest

A generator builds {repo-relative path: file text}; run() writes the files plus a
MANIFEST.json, or with --check regenerates in memory and compares. The manifest
records the command, the sha256 of every generator source file, the Python and
mpmath versions, mp.dps and the sha256 of every output. python_version and
mpmath_backend are recorded but not compared, because neither changes results.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import platform
import statistics
import sys
from collections.abc import Callable
from pathlib import Path

import mpmath
from mpmath import mp, mpf

MPMATH_VERSION = "1.4.1"
DPS = 50
ROOT = Path(__file__).resolve().parent.parent
TABLEGEN = "tools/tablegen.py"


# --- conversions --------------------------------------------------------------------


def to_double(x: mpf) -> float:
    """Round an mpf once to binary64 (overflow -> +-inf)."""
    try:
        return float(x)
    except OverflowError:
        return math.inf if x > 0 else -math.inf


def cxx(v: float) -> str:
    """Exact C++17 hexadecimal floating literal."""
    assert math.isfinite(v), v
    return v.hex()


def row(*cells: object) -> str:
    return ",".join(str(c) for c in cells) + "\n"


def pow10(e: mpf) -> float:
    return to_double(mpf(10) ** e)


def command(generator: str) -> str:
    return f"uv run --no-project --with mpmath=={MPMATH_VERSION} python {generator}"


def header_banner(generator: str, manifest: str) -> str:
    return (
        "// SPDX-License-Identifier: Apache-2.0\n"
        f"// GENERATED by {generator} (mpmath {MPMATH_VERSION}, dps {DPS}). Do not edit.\n"
        f"// Provenance: {manifest}. Regenerate with:\n"
        f"//   {command(generator)}\n"
    )


def csv_note(generator: str) -> str:
    return f"# GENERATED by {generator}; see MANIFEST.json. *_hex columns are exact; decimal columns are for reading.\n"


# --- mpmath reference functions ------------------------------------------------------

# mpmath's erfc overflows near x = 1e300, so reference erfcx uses the asymptotic
# series from here on; the two are cross-checked where both are usable (D-072).
ERFCX_ASYMPTOTIC_FROM = 100
# Likewise ncdf(x) near x = -1e155, so reference log Phi switches to erfcx below this.
LOG_PHI_ERFCX_BELOW = -200


def erfcx_mp(x: mpf) -> mpf:
    if x >= ERFCX_ASYMPTOTIC_FROM:
        return erfcx_asymptotic(x)
    return mp.exp(x * x) * mp.erfc(x)


def erfcx_asymptotic(x: mpf) -> mpf:
    # erfcx(x) = 1/(x sqrt(pi)) * sum_n (-1)^n (2n-1)!! / (2x^2)^n. For x >= 100 the
    # terms fall below 1e-100 relative well before n = 30.
    s, term = mpf(0), mpf(1)
    for n in range(30):
        s += term
        term *= -(2 * n + 1) / (2 * x * x)
    return s / (x * mp.sqrt(mp.pi))


def log_phi_mp(x: mpf) -> mpf:
    if x <= LOG_PHI_ERFCX_BELOW:
        return log_phi_via_erfcx(x)
    if x <= 0:
        return mp.log(mp.ncdf(x))
    return mp.log1p(-mp.ncdf(-x))  # keeps relative accuracy where log Phi -> 0


def log_phi_via_erfcx(x: mpf) -> mpf:
    # Phi(x) = erfcx(-x/sqrt 2) exp(-x^2/2) / 2; used where mpmath's ncdf overflows.
    return mp.log(erfcx_mp(-x / mp.sqrt(2)) / 2) - x * x / 2


def probit_mp(p: mpf) -> mpf:
    half = mpf(1) / 2
    if p > half:
        return -probit_mp(1 - p)  # 1 - p is exact at DPS for any binary64 p
    if p == half:
        return mpf(0)
    x = mpf(statistics.NormalDist().inv_cdf(float(p)))  # starting point only
    target = mp.log(p)
    for _ in range(60):
        step = (mp.log(mp.ncdf(x)) - target) * mp.ncdf(x) / mp.npdf(x)
        x -= step
        if abs(step) < mpf(10) ** (-DPS + 5) * max(1, abs(x)):
            break
    else:
        raise RuntimeError(f"probit Newton did not converge for p={p}")
    assert abs(mp.log(mp.ncdf(x)) - target) <= mpf(10) ** (-DPS + 8) * abs(target)
    return x


def reference_self_checks() -> None:
    for x in (100, 1000, 10000):
        a, b = erfcx_asymptotic(mpf(x)), mp.exp(mpf(x) ** 2) * mp.erfc(mpf(x))
        assert abs(a / b - 1) < mpf(10) ** -45, ("erfcx asymptotic vs erfc", x)
    for x in (-200, -1000):
        a, b = log_phi_via_erfcx(mpf(x)), mp.log(mp.ncdf(mpf(x)))
        assert abs(a / b - 1) < mpf(10) ** -45, ("log Phi via erfcx vs ncdf", x)


# --- driver -------------------------------------------------------------------------


def _sha256_text(path: str) -> str:
    return hashlib.sha256((ROOT / path).read_bytes().replace(b"\r\n", b"\n")).hexdigest()


def _manifest_for_compare(text: str) -> dict:
    data = json.loads(text)
    data.pop("python_version", None)
    data.pop("mpmath_backend", None)
    return data


def run(generator: str, manifest: str, build_outputs: Callable[[], dict[str, str]], doc: str) -> int:
    parser = argparse.ArgumentParser(description=doc, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="verify checked-in files instead of writing")
    args = parser.parse_args()

    if mpmath.__version__ != MPMATH_VERSION:
        print(f"need mpmath {MPMATH_VERSION}, have {mpmath.__version__}", file=sys.stderr)
        return 2
    mp.dps = DPS
    reference_self_checks()

    outputs = build_outputs()
    manifest_data = {
        "command": command(generator),
        "generator_files": {path: _sha256_text(path) for path in sorted({generator, TABLEGEN})},
        "python_version": platform.python_version(),
        "mpmath_version": mpmath.__version__,
        "mpmath_backend": mpmath.libmp.BACKEND,
        "mp_dps": DPS,
        "outputs": {path: hashlib.sha256(text.encode()).hexdigest() for path, text in sorted(outputs.items())},
    }
    outputs[manifest] = json.dumps(manifest_data, indent=2, sort_keys=True) + "\n"

    if not args.check:
        for path, text in outputs.items():
            target = ROOT / path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text, encoding="utf-8", newline="\n")
            print(f"wrote {path}")
        return 0

    stale = []
    for path, text in outputs.items():
        target = ROOT / path
        if not target.exists():
            stale.append(f"missing: {path}")
            continue
        on_disk = target.read_bytes().replace(b"\r\n", b"\n").decode("utf-8")
        if path == manifest:
            same = _manifest_for_compare(on_disk) == _manifest_for_compare(text)
        else:
            same = on_disk == text
        if not same:
            stale.append(f"differs: {path}")
    for line in stale:
        print(line, file=sys.stderr)
    print("generated files are up to date" if not stale else f"{len(stale)} generated file(s) out of date")
    return 1 if stale else 0
